// <auto-generated />
using System;
using CurrencyFxOData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CurrencyFxOData.Migrations
{
    [DbContext(typeof(FxDbContext))]
    [Migration("20260215042136_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CurrencyFxOData.Models.CurrencyFXRate", b =>
                {
                    b.Property<string>("UniqueNameDate")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<decimal>("CorporateDailyInvoiceInverseRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("CorporateDailyInvoiceRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("CorporateMonthEndInverseRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("CorporateMonthEndRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("CurrencyFrom")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("CurrencyTo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("RateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("UniqueNameDate");

                    b.HasIndex("RateDate");

                    b.ToTable("CurrencyFXRates");
                });
#pragma warning restore 612, 618
        }
    }
}
